import type { Lesson } from "./types";

export const PHASE1: Record<number, Lesson> = {
  1: {
    body: "<h3>핵심 개념</h3><p>CPU는 놀랄 만큼 단순한 반복 기계입니다. <b>PC(Program Counter)</b>가 가리키는 주소에서 명령어를 읽고(fetch), 그것이 무슨 일인지 해석해 제어 신호로 바꾸고(decode), 실행합니다(execute). 실행이 끝나면 PC를 다음 명령어로 갱신하고 처음부터 반복 — 이 사이클을 초당 수십억 번 돕니다.</p><p>이 과정에 등장하는 저장 공간이 <b>레지스터</b>입니다. PC는 다음 명령어의 주소를, IR(Instruction Register)은 현재 실행 중인 명령어 자체를, 범용 레지스터들은 연산의 피연산자와 결과를 담습니다. 레지스터 접근은 1ns 미만이지만 RAM은 ~100ns — 이 100배의 간극이 내일 배울 캐시가 존재하는 이유입니다.</p><h3>파이프라이닝</h3><p>fetch가 끝난 명령어가 decode되는 동안, CPU는 놀지 않고 다음 명령어를 fetch합니다. 세탁기·건조기·다림질을 겹쳐 돌리는 것과 같은 원리로, 명령어 <b>하나의 소요 시간(latency)은 그대로</b>지만 <b>단위 시간당 처리량(throughput)</b>이 늘어납니다.</p><p>문제는 분기(if)입니다. 조건 결과가 나오기 전에는 다음에 뭘 fetch할지 모르므로 CPU는 <b>분기 예측</b>으로 미리 채워 넣습니다. 예측이 틀리면 미리 채운 작업을 전부 버리고(flush) 다시 시작 — \"정렬된 배열에서 조건 분기가 훨씬 빠르다\"는 유명한 벤치마크가 여기서 나옵니다.</p>",
    svg: "<svg viewBox=\"0 0 640 190\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><defs><marker id=\"a1\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#5F6B7E\"/></marker></defs><rect x=\"30\" y=\"30\" width=\"130\" height=\"52\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"95\" y=\"52\" text-anchor=\"middle\" font-size=\"14\" font-weight=\"700\" fill=\"#1B2432\">Fetch</text><text x=\"95\" y=\"70\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">PC 주소의 명령어 읽기</text><rect x=\"255\" y=\"30\" width=\"130\" height=\"52\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"320\" y=\"52\" text-anchor=\"middle\" font-size=\"14\" font-weight=\"700\" fill=\"#1B2432\">Decode</text><text x=\"320\" y=\"70\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">제어 신호로 해석</text><rect x=\"480\" y=\"30\" width=\"130\" height=\"52\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"545\" y=\"52\" text-anchor=\"middle\" font-size=\"14\" font-weight=\"700\" fill=\"#1B2432\">Execute</text><text x=\"545\" y=\"70\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">ALU 연산 / 메모리 / 분기</text><line x1=\"160\" y1=\"56\" x2=\"253\" y2=\"56\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a1)\"/><line x1=\"385\" y1=\"56\" x2=\"478\" y2=\"56\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a1)\"/><path d=\"M545,82 L545,130 L95,130 L95,84\" fill=\"none\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a1)\" stroke-dasharray=\"4 3\"/><text x=\"320\" y=\"147\" text-anchor=\"middle\" font-size=\"11\" fill=\"#5F6B7E\">PC 갱신 후 반복 (파이프라이닝: 세 단계를 서로 다른 명령어가 동시에 사용)</text><text x=\"320\" y=\"175\" text-anchor=\"middle\" font-size=\"11\" fill=\"#D97D00\" font-weight=\"600\">레지스터 &lt;1ns · RAM ~100ns → 이 간극이 캐시의 존재 이유</text></svg>",
    quiz: [
      { q: "PC(Program Counter)의 역할은?", opts: ["다음에 실행할 명령어의 주소를 저장한다","현재 실행 중인 명령어 자체를 저장한다","연산의 중간 결과를 저장한다"], ans: 0, why: "명령어 자체는 IR, 연산 결과는 범용 레지스터의 몫입니다. PC는 오직 '다음 위치'만 추적합니다." },
      { q: "파이프라이닝이 직접적으로 개선하는 것은?", opts: ["명령어 하나의 처리 시간(latency)","단위 시간당 처리량(throughput)","레지스터 접근 속도"], ans: 1, why: "각 명령어는 여전히 모든 단계를 거치므로 latency는 그대로입니다. 단계들이 겹쳐 돌면서 초당 완료되는 명령어 수가 늘어납니다." },
      { q: "분기 예측이 실패하면 무슨 일이 벌어지나?", opts: ["CPU가 해당 프로세스를 종료한다","미리 채워 둔 파이프라인을 버리고(flush) 올바른 경로에서 다시 시작한다","OS가 페이지 폴트를 발생시킨다"], ans: 1, why: "flush 비용은 파이프라인 깊이만큼의 사이클 손실입니다. 예측 가능한(정렬된) 데이터에서 분기가 빨라지는 이유입니다." },
    ],
  },
  2: {
    body: "<h3>계층이 존재하는 이유</h3><p>빠른 메모리는 비싸고 작습니다. 그래서 컴퓨터는 하나의 큰 메모리 대신 <b>계층</b>을 씁니다: 레지스터(&lt;1ns) → L1 캐시(~1ns, 수십KB) → L2(~4ns) → L3(~10-30ns, 수십MB) → RAM(~100ns) → SSD(~100µs). 아래로 갈수록 100배씩 느려지고 1000배씩 커진다고 기억하면 대략 맞습니다.</p><h3>캐시 라인과 지역성</h3><p>캐시는 데이터를 1바이트씩이 아니라 <b>캐시 라인(보통 64바이트)</b> 단위로 가져옵니다. <code>arr[0]</code>을 읽으면 <code>arr[1..15]</code>(int 기준)도 함께 올라온다는 뜻입니다.</p><p>이 설계는 두 가지 <b>지역성(locality)</b> 가정에 기반합니다. <b>시간 지역성</b>: 방금 쓴 데이터는 곧 또 쓴다(루프 변수). <b>공간 지역성</b>: 어떤 주소를 쓰면 그 근처도 곧 쓴다(배열 순회). 하드웨어가 이 가정에 최적화되어 있으므로, <b>이 가정을 따르는 코드가 빠른 코드</b>입니다. 같은 O(n)이라도 배열 순차 순회가 연결 리스트 순회보다 수배~수십배 빠른 근본 이유가 여기 있습니다(Day 14에서 재등장).</p>",
    svg: "<svg viewBox=\"0 0 640 230\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><g text-anchor=\"middle\" font-size=\"12\"><rect x=\"245\" y=\"15\" width=\"150\" height=\"30\" rx=\"6\" fill=\"#D97D00\"/><text x=\"320\" y=\"35\" fill=\"#fff\" font-weight=\"700\">레지스터 &lt;1ns</text><rect x=\"215\" y=\"52\" width=\"210\" height=\"30\" rx=\"6\" fill=\"#E8963A\"/><text x=\"320\" y=\"72\" fill=\"#fff\" font-weight=\"700\">L1 ~1ns · 64KB</text><rect x=\"185\" y=\"89\" width=\"270\" height=\"30\" rx=\"6\" fill=\"#F0B26E\"/><text x=\"320\" y=\"109\" fill=\"#1B2432\" font-weight=\"700\">L2 ~4ns · 1MB</text><rect x=\"155\" y=\"126\" width=\"330\" height=\"30\" rx=\"6\" fill=\"#F7CEA0\"/><text x=\"320\" y=\"146\" fill=\"#1B2432\" font-weight=\"700\">L3 ~20ns · 32MB</text><rect x=\"125\" y=\"163\" width=\"390\" height=\"30\" rx=\"6\" fill=\"#DCE3ED\"/><text x=\"320\" y=\"183\" fill=\"#1B2432\" font-weight=\"700\">RAM ~100ns · 수십 GB</text><rect x=\"95\" y=\"200\" width=\"450\" height=\"26\" rx=\"6\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"320\" y=\"217\" fill=\"#5F6B7E\" font-weight=\"700\">SSD ~100µs (RAM의 1000배 느림)</text></g><text x=\"70\" y=\"40\" font-size=\"11\" fill=\"#5F6B7E\">빠름·작음</text><text x=\"70\" y=\"215\" font-size=\"11\" fill=\"#5F6B7E\">느림·큼</text><line x1=\"75\" y1=\"50\" x2=\"75\" y2=\"195\" stroke=\"#5F6B7E\" stroke-width=\"1.5\"/></svg>",
    quiz: [
      { q: "캐시가 64바이트 '라인' 단위로 데이터를 가져오는 것은 어떤 가정에 기반하나?", opts: ["시간 지역성 — 방금 쓴 것을 또 쓴다","공간 지역성 — 근처 데이터를 곧 쓴다","참조 무결성 — 포인터는 유효하다"], ans: 1, why: "한 주소를 읽을 때 이웃까지 미리 올려 두는 건 '근처를 곧 쓸 것'이라는 공간 지역성 베팅입니다." },
      { q: "2차원 배열(row-major)을 순회할 때 <code>for(i){for(j){a[i][j]}}</code>가 <code>a[j][i]</code> 순회보다 빠른 이유는?", opts: ["연산 횟수가 더 적어서","메모리를 순차 접근해 캐시 라인을 최대로 활용해서","컴파일러가 i-j 순서만 최적화해서"], ans: 1, why: "연산 횟수(Big-O)는 동일합니다. 차이는 캐시 미스 횟수 — 순차 접근은 라인 하나로 여러 원소를 처리하지만, 열 우선 접근은 매번 새 라인을 불러옵니다." },
      { q: "L1 캐시 히트와 RAM 접근의 속도 차이는 대략?", opts: ["~2배","~10배","~100배"], ans: 2, why: "1ns vs 100ns. 캐시 미스가 잦은 코드는 CPU가 대부분의 시간을 '기다림'에 쓴다는 뜻입니다." },
    ],
  },
  3: {
    body: "<h3>정의부터 정확히</h3><p><b>프로세스</b>는 실행 중인 프로그램 인스턴스로, 독립된 가상 주소 공간·파일 디스크립터·자원을 가집니다. <b>스레드</b>는 프로세스 안의 실행 흐름입니다. 같은 프로세스의 스레드들은 <b>코드, 힙, 전역 변수를 공유</b>하고, <b>스택과 레지스터(PC 포함)는 각자</b> 가집니다.</p><h3>공유의 양날</h3><p>공유 덕분에 스레드 간 통신은 그냥 같은 객체를 읽으면 될 만큼 쉽고 생성 비용도 저렴합니다. 대신 두 스레드가 같은 데이터를 동시에 건드리면 경쟁 상태가 생기므로 동기화(Day 6)가 필요합니다. 프로세스는 반대입니다: 격리되어 있어 하나가 죽어도 다른 프로세스는 안전하지만, 통신하려면 IPC(파이프, 소켓, 공유 메모리)라는 비용을 치릅니다.</p><h3>Node.js는 어디에 있나</h3><p>Node는 \"JS 실행은 스레드 1개\"라는 선택을 했습니다. 대신 I/O는 이벤트 루프로 겹치고(Day 10), CPU 무거운 작업은 <code>worker_threads</code>(스레드)나 <code>cluster</code>(프로세스)로 넘깁니다. cluster가 크래시 격리에 유리하고, worker가 메모리 공유(ArrayBuffer 전달)에 유리한 이유가 오늘 내용 그대로입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 220\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><rect x=\"20\" y=\"20\" width=\"290\" height=\"180\" rx=\"12\" fill=\"#fff\" stroke=\"#D97D00\" stroke-width=\"1.5\"/><text x=\"165\" y=\"44\" text-anchor=\"middle\" font-size=\"13\" font-weight=\"700\" fill=\"#D97D00\">프로세스 A</text><rect x=\"40\" y=\"58\" width=\"250\" height=\"34\" rx=\"6\" fill=\"#FBEEDC\"/><text x=\"165\" y=\"79\" text-anchor=\"middle\" font-size=\"11.5\" fill=\"#1B2432\">공유: 코드 · 힙 · 전역 변수</text><rect x=\"40\" y=\"104\" width=\"115\" height=\"80\" rx=\"8\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"97\" y=\"126\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"#1B2432\">스레드 1</text><text x=\"97\" y=\"146\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">스택 · 레지스터</text><text x=\"97\" y=\"162\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">(각자 소유)</text><rect x=\"175\" y=\"104\" width=\"115\" height=\"80\" rx=\"8\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"232\" y=\"126\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"#1B2432\">스레드 2</text><text x=\"232\" y=\"146\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">스택 · 레지스터</text><text x=\"232\" y=\"162\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">(각자 소유)</text><rect x=\"350\" y=\"20\" width=\"270\" height=\"180\" rx=\"12\" fill=\"#fff\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" stroke-dasharray=\"5 4\"/><text x=\"485\" y=\"44\" text-anchor=\"middle\" font-size=\"13\" font-weight=\"700\" fill=\"#5F6B7E\">프로세스 B (독립 주소 공간)</text><text x=\"485\" y=\"100\" text-anchor=\"middle\" font-size=\"11.5\" fill=\"#5F6B7E\">A와 메모리를 공유하지 않음</text><text x=\"485\" y=\"122\" text-anchor=\"middle\" font-size=\"11.5\" fill=\"#5F6B7E\">통신하려면 IPC 필요</text><text x=\"485\" y=\"144\" text-anchor=\"middle\" font-size=\"11.5\" fill=\"#2E6B4F\">A가 죽어도 B는 안전 (격리)</text></svg>",
    quiz: [
      { q: "같은 프로세스의 스레드들이 공유하지 <b>않는</b> 것은?", opts: ["힙","전역 변수","스택"], ans: 2, why: "각 스레드는 자기만의 호출 스택과 레지스터를 가집니다. 함수의 지역 변수가 스레드마다 독립인 이유입니다." },
      { q: "멀티프로세스 대비 멀티스레드의 대표적 장점은?", opts: ["하나가 죽어도 나머지가 안전하다","메모리를 공유해 통신이 빠르고 생성 비용이 낮다","동기화가 필요 없다"], ans: 1, why: "격리(a)는 프로세스의 장점이고, 동기화(c)는 오히려 스레드에서 더 필요해집니다." },
      { q: "Node에서 요청 처리 중 하나의 워커가 죽어도 서비스를 유지하고 싶다면 더 적합한 것은?", opts: ["worker_threads","cluster(멀티프로세스)","둘 다 동일하다"], ans: 1, why: "프로세스 격리 덕분에 한 워커의 크래시가 다른 워커에 전파되지 않습니다. worker_threads는 같은 프로세스라 치명적 크래시에 함께 노출됩니다." },
    ],
  },
  4: {
    body: "<h3>스케줄러의 딜레마</h3><p>실행 가능한 작업은 많고 CPU 코어는 적습니다. 누구에게 먼저 줄 것인가? 목표들이 서로 충돌합니다: <b>처리량</b>(전체 완료량 최대화), <b>응답 시간</b>(대화형 작업이 빨리 반응), <b>공정성</b>(굶는 작업이 없게). 하나를 올리면 다른 게 내려갑니다.</p><h3>대표 알고리즘의 진화</h3><p><b>FCFS</b>(선착순)는 단순하지만 긴 작업 뒤에 짧은 작업들이 줄줄이 기다리는 <b>convoy effect</b>가 생깁니다. <b>SJF</b>(짧은 것 먼저)는 평균 대기시간이 이론상 최적이지만 각 작업이 얼마나 걸릴지 미리 알 수 없다는 치명적 문제가 있습니다.</p><p><b>RR</b>(Round Robin)은 <b>타임 퀀텀</b>만큼씩 돌아가며 실행합니다(선점형). 퀀텀이 너무 작으면 컨텍스트 스위칭 오버헤드(Day 8)가 지배하고, 너무 크면 FCFS와 다를 게 없어집니다. <b>MLFQ</b>(다단계 피드백 큐)는 여러 우선순위 큐를 두고, CPU를 오래 쓰는 작업은 아래 큐로 강등, I/O 후 돌아오는 대화형 작업은 위 큐 유지 — \"미래를 모른다\"는 SJF의 문제를 <b>과거 행동 관찰로 근사</b>한 것으로, 실제 OS 스케줄러들의 원형입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 210\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"28\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">FCFS — convoy effect</text><rect x=\"20\" y=\"38\" width=\"300\" height=\"24\" fill=\"#F0B26E\" rx=\"4\"/><text x=\"170\" y=\"54\" text-anchor=\"middle\" font-size=\"11\" fill=\"#1B2432\">긴 작업 (30ms)</text><rect x=\"324\" y=\"38\" width=\"40\" height=\"24\" fill=\"#DCE3ED\" rx=\"4\"/><rect x=\"368\" y=\"38\" width=\"40\" height=\"24\" fill=\"#DCE3ED\" rx=\"4\"/><text x=\"430\" y=\"54\" font-size=\"10.5\" fill=\"#B3392E\">← 짧은 작업들이 뒤에서 대기</text><text x=\"20\" y=\"98\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">RR (퀀텀 10ms) — 번갈아 실행</text><g font-size=\"10\" text-anchor=\"middle\"><rect x=\"20\" y=\"108\" width=\"60\" height=\"24\" fill=\"#F0B26E\" rx=\"4\"/><text x=\"50\" y=\"124\" fill=\"#1B2432\">긴¹</text><rect x=\"84\" y=\"108\" width=\"60\" height=\"24\" fill=\"#DCE3ED\" rx=\"4\"/><text x=\"114\" y=\"124\" fill=\"#1B2432\">짧A ✓</text><rect x=\"148\" y=\"108\" width=\"60\" height=\"24\" fill=\"#DCE3ED\" rx=\"4\"/><text x=\"178\" y=\"124\" fill=\"#1B2432\">짧B ✓</text><rect x=\"212\" y=\"108\" width=\"60\" height=\"24\" fill=\"#F0B26E\" rx=\"4\"/><text x=\"242\" y=\"124\" fill=\"#1B2432\">긴²</text><rect x=\"276\" y=\"108\" width=\"60\" height=\"24\" fill=\"#F0B26E\" rx=\"4\"/><text x=\"306\" y=\"124\" fill=\"#1B2432\">긴³</text></g><text x=\"20\" y=\"152\" font-size=\"11\" fill=\"#2E6B4F\">짧은 작업이 빨리 끝남 — 응답성 ↑, 대신 스위칭 비용 발생</text><text x=\"20\" y=\"188\" font-size=\"11.5\" fill=\"#5F6B7E\">MLFQ = \"CPU를 오래 쓰면 강등, I/O로 양보하면 우선\" — 과거 행동으로 미래를 근사</text></svg>",
    quiz: [
      { q: "convoy effect란?", opts: ["짧은 작업들이 긴 작업 뒤에 몰려 평균 대기시간이 폭증하는 현상","캐시 라인이 연쇄적으로 무효화되는 현상","프로세스들이 서로를 기다리며 영원히 멈추는 현상"], ans: 0, why: "(c)는 데드락입니다. convoy는 FCFS처럼 비선점 스케줄링에서 두드러집니다." },
      { q: "RR의 타임 퀀텀을 극단적으로 줄이면?", opts: ["FCFS와 동일해진다","컨텍스트 스위칭 오버헤드가 실제 작업 시간을 압도한다","평균 대기시간이 항상 최소가 된다"], ans: 1, why: "퀀텀을 극단적으로 키우면 (a)가 됩니다. 퀀텀은 응답성과 오버헤드 사이의 다이얼입니다." },
      { q: "MLFQ에서 CPU를 퀀텀 끝까지 계속 쓰는 작업은 어떻게 되나?", opts: ["우선순위가 낮은 큐로 강등된다","즉시 종료된다","가장 높은 큐로 승격된다"], ans: 0, why: "CPU를 오래 점유하는 배치성 작업을 아래로 보내, I/O 위주의 대화형 작업이 빠르게 반응하도록 만드는 것이 MLFQ의 핵심입니다." },
    ],
  },
  5: {
    body: "<h3>거대한 거짓말</h3><p>가상 메모리는 각 프로세스에게 \"너 혼자 연속된 메모리 전체를 쓰고 있다\"고 속이는 추상화입니다. 프로세스가 쓰는 <b>가상 주소</b>는 <b>페이지 테이블</b>을 거쳐 실제 <b>물리 주소</b>로 변환됩니다. 변환 단위가 <b>페이지</b>(보통 4KB)입니다.</p><h3>TLB와 페이지 폴트</h3><p>모든 메모리 접근마다 페이지 테이블(RAM에 있음)을 찾아가면 접근이 2배가 됩니다. 그래서 CPU 안에 최근 변환 결과를 캐시하는 <b>TLB</b>를 둡니다 — 어제 배운 캐시 원리가 주소 변환에도 그대로 적용된 것입니다.</p><p>접근한 페이지가 물리 메모리에 없으면 <b>페이지 폴트</b>가 발생하고, OS가 디스크에서 해당 페이지를 로드합니다. 비용은 수 ms — CPU 사이클로는 <b>수백만 사이클</b>입니다. \"메모리가 부족하면 느려진다\"의 정체가 바로 이 스와핑입니다.</p><h3>무엇을 얻나</h3><p>격리(프로세스끼리 서로의 메모리를 볼 수 없음 — Day 3의 전제), 물리 메모리보다 큰 주소 공간, 공유 라이브러리(같은 물리 페이지를 여러 프로세스의 가상 주소에 매핑), 그리고 fork의 copy-on-write 같은 트릭이 전부 이 한 겹의 간접화에서 나옵니다.</p>",
    svg: "<svg viewBox=\"0 0 640 200\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><defs><marker id=\"a5\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#5F6B7E\"/></marker></defs><rect x=\"20\" y=\"60\" width=\"140\" height=\"70\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"90\" y=\"88\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">가상 주소</text><text x=\"90\" y=\"108\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">프로세스가 보는 세계</text><rect x=\"250\" y=\"60\" width=\"150\" height=\"70\" rx=\"10\" fill=\"#fff\" stroke=\"#5F6B7E\"/><text x=\"325\" y=\"83\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">페이지 테이블</text><text x=\"325\" y=\"101\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">페이지 단위 매핑</text><text x=\"325\" y=\"117\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#D97D00\">TLB가 결과를 캐시</text><rect x=\"490\" y=\"60\" width=\"130\" height=\"70\" rx=\"10\" fill=\"#EAF3EE\" stroke=\"#2E6B4F\"/><text x=\"555\" y=\"88\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">물리 주소</text><text x=\"555\" y=\"108\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">실제 RAM</text><line x1=\"160\" y1=\"95\" x2=\"248\" y2=\"95\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a5)\"/><line x1=\"400\" y1=\"95\" x2=\"488\" y2=\"95\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a5)\"/><path d=\"M325,132 L325,165\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a5)\" stroke-dasharray=\"4 3\"/><text x=\"325\" y=\"185\" text-anchor=\"middle\" font-size=\"11\" fill=\"#B3392E\">페이지가 RAM에 없으면 → 페이지 폴트 → 디스크 로드 (수백만 사이클)</text></svg>",
    quiz: [
      { q: "TLB의 역할은?", opts: ["디스크 블록을 캐시한다","가상→물리 주소 변환 결과를 캐시한다","자주 쓰는 명령어를 캐시한다"], ans: 1, why: "TLB 미스가 나면 페이지 테이블을 직접 조회해야 하므로 메모리 접근이 추가로 발생합니다." },
      { q: "서로 다른 두 프로세스가 같은 가상 주소 0x1000을 쓰고 있다. 가능한 일인가?", opts: ["불가능하다 — 주소는 유일해야 한다","가능하다 — 각자의 페이지 테이블이 다른 물리 주소로 매핑한다","공유 메모리를 선언했을 때만 가능하다"], ans: 1, why: "가상 주소 공간은 프로세스마다 독립입니다. 이것이 격리의 메커니즘 그 자체입니다." },
      { q: "L1 캐시 히트(~1ns) 대비 페이지 폴트의 비용 규모는?", opts: ["~10배","~1,000배","~1,000,000배 이상"], ans: 2, why: "디스크 I/O는 ms 단위입니다. 성능 문제의 원인이 계층의 어디에 있는지에 따라 대응이 완전히 달라지는 이유입니다." },
    ],
  },
  6: {
    body: "<h3>경쟁 상태(race condition)</h3><p>결과가 실행 <b>타이밍</b>에 따라 달라지는 버그입니다. 고전 예시: 두 스레드가 <code>counter++</code>를 실행. 이 한 줄은 사실 read → +1 → write의 3단계라서, 두 스레드의 단계가 인터리빙되면 둘 다 같은 값을 읽고 둘 다 +1을 써서 <b>증가 하나가 사라집니다</b>.</p><h3>도구들</h3><p>동시에 실행되면 안 되는 코드 구간이 <b>임계 구역</b>입니다. <b>뮤텍스</b>는 열쇠가 1개인 자물쇠 — 잠근 스레드만 풀 수 있습니다(소유 개념). <b>세마포어</b>는 카운터 — N개까지 동시 진입을 허용하고, 소유 개념이 없어 \"일이 준비됐다\"는 신호 전달에도 씁니다. DB 커넥션 풀(최대 N개)이 세마포어의 전형적 사용처입니다.</p><h3>\"JS는 싱글 스레드라 안전하다\"의 함정</h3><p>메모리 수준의 데이터 레이스는 없지만, <b>논리적 레이스</b>는 있습니다. <code>await</code> 지점마다 다른 코드가 끼어들 수 있기 때문입니다. 잔액을 <b>확인하고(check)</b> await로 외부 API를 기다린 뒤 <b>차감하면(act)</b>, 그 사이에 다른 요청이 잔액을 바꿨을 수 있습니다 — 전형적인 check-then-act 레이스이고, DB 트랜잭션이나 낙관적 락(Day 40)으로 막습니다.</p>",
    svg: "<svg viewBox=\"0 0 640 210\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"26\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">두 스레드의 counter++ (초기값 5) — 증가 하나가 사라진다</text><g font-size=\"11\"><text x=\"20\" y=\"60\" font-weight=\"700\" fill=\"#D97D00\">스레드 A</text><rect x=\"90\" y=\"46\" width=\"110\" height=\"22\" rx=\"4\" fill=\"#FBEEDC\"/><text x=\"145\" y=\"61\" text-anchor=\"middle\">read → 5</text><rect x=\"330\" y=\"46\" width=\"110\" height=\"22\" rx=\"4\" fill=\"#FBEEDC\"/><text x=\"385\" y=\"61\" text-anchor=\"middle\">write 6</text><text x=\"20\" y=\"105\" font-weight=\"700\" fill=\"#5F6B7E\">스레드 B</text><rect x=\"210\" y=\"91\" width=\"110\" height=\"22\" rx=\"4\" fill=\"#DCE3ED\"/><text x=\"265\" y=\"106\" text-anchor=\"middle\">read → 5</text><rect x=\"450\" y=\"91\" width=\"110\" height=\"22\" rx=\"4\" fill=\"#DCE3ED\"/><text x=\"505\" y=\"106\" text-anchor=\"middle\">write 6</text></g><line x1=\"20\" y1=\"130\" x2=\"620\" y2=\"130\" stroke=\"#D8DFE9\"/><text x=\"20\" y=\"152\" font-size=\"11.5\" fill=\"#B3392E\" font-weight=\"600\">결과: 6 (기대값 7) — B가 A의 write 전에 read했기 때문</text><text x=\"20\" y=\"182\" font-size=\"11.5\" fill=\"#2E6B4F\">해결: read~write 전체를 임계 구역으로 묶어 원자적으로 실행 (뮤텍스)</text></svg>",
    quiz: [
      { q: "<code>counter++</code>가 동시성 환경에서 위험한 근본 이유는?", opts: ["++ 연산자가 느려서","read-modify-write 3단계가 원자적이지 않아 인터리빙될 수 있어서","counter가 캐시에 올라가지 않아서"], ans: 1, why: "단계 사이에 다른 스레드가 끼어들 수 있다는 것이 문제의 전부입니다. 원자적 연산이나 락으로 '끼어들 수 없게' 만들어야 합니다." },
      { q: "뮤텍스와 세마포어의 핵심 차이는?", opts: ["뮤텍스는 소유 개념이 있는 1개짜리 자물쇠, 세마포어는 N까지 허용하는 카운터","뮤텍스가 항상 더 빠르다","세마포어는 커널에서만 쓸 수 있다"], ans: 0, why: "동시 접속 N개 제한(커넥션 풀), 생산자-소비자 신호 전달 등은 세마포어의 영역입니다." },
      { q: "싱글 스레드 JS에서도 레이스가 생기는 지점은?", opts: ["동기 for 루프 내부","await 경계 — 기다리는 동안 다른 코드가 상태를 바꿀 수 있다","const 선언부"], ans: 1, why: "check-then-act 패턴에서 check와 act 사이에 await가 있으면, 그 사이 상태 변경을 의심해야 합니다." },
    ],
  },
  7: {
    body: "<h3>데드락의 4가지 필요조건</h3><p>다음 <b>네 조건이 모두</b> 성립할 때만 데드락이 가능합니다. ① <b>상호 배제</b>: 자원을 한 번에 하나만 사용. ② <b>점유와 대기</b>: 자원을 쥔 채 다른 자원을 기다림. ③ <b>비선점</b>: 남의 자원을 강제로 뺏을 수 없음. ④ <b>순환 대기</b>: A→B→…→A로 기다림이 원을 이룸. 뒤집어 말하면, <b>하나만 깨면 데드락은 불가능</b>합니다.</p><h3>실무의 대응 3종</h3><p><b>예방</b>: 조건 하나를 구조적으로 제거. 가장 실용적인 것은 <b>락 획득 순서를 전역적으로 고정</b>하는 것 — 모두가 락1→락2 순서로만 잡으면 순환이 생길 수 없습니다(④ 제거). <b>회피</b>: 은행원 알고리즘처럼 위험한 할당을 거부 — 미래의 요구량을 알아야 해서 실무에선 드뭅니다. <b>탐지+회복</b>: 일단 두고, 순환을 발견하면 하나를 희생. <b>DB가 쓰는 방식</b>입니다 — 데드락을 감지하면 한 트랜잭션을 강제 롤백하고 에러를 던집니다. 애플리케이션에 재시도 로직이 필요한 이유입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 220\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><defs><marker id=\"a7\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#B3392E\"/></marker></defs><rect x=\"80\" y=\"30\" width=\"150\" height=\"50\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"155\" y=\"51\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\">트랜잭션 A</text><text x=\"155\" y=\"68\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">락1 보유 · 락2 대기</text><rect x=\"410\" y=\"140\" width=\"150\" height=\"50\" rx=\"10\" fill=\"#DCE3ED\" stroke=\"#5F6B7E\"/><text x=\"485\" y=\"161\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\">트랜잭션 B</text><text x=\"485\" y=\"178\" text-anchor=\"middle\" font-size=\"10.5\" fill=\"#5F6B7E\">락2 보유 · 락1 대기</text><path d=\"M230,65 C330,80 400,110 425,138\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a7)\"/><text x=\"360\" y=\"90\" font-size=\"10.5\" fill=\"#B3392E\">락2를 기다림</text><path d=\"M410,160 C300,150 200,120 145,82\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a7)\"/><text x=\"235\" y=\"140\" font-size=\"10.5\" fill=\"#B3392E\">락1을 기다림</text><text x=\"320\" y=\"212\" text-anchor=\"middle\" font-size=\"11.5\" fill=\"#2E6B4F\">해법: 모두가 락1 → 락2 순서로만 획득하면 이 원은 생길 수 없다 (순환 대기 제거)</text></svg>",
    quiz: [
      { q: "'모든 코드는 락을 반드시 락1→락2 순서로 획득한다'는 규칙이 깨뜨리는 조건은?", opts: ["상호 배제","비선점","순환 대기"], ans: 2, why: "전역 순서가 있으면 대기 그래프에 사이클이 생길 수 없습니다. 가장 널리 쓰이는 데드락 예방책입니다." },
      { q: "DB에서 데드락이 감지되면 일반적으로 일어나는 일은?", opts: ["두 트랜잭션 모두 무기한 대기한다","한 트랜잭션이 희생양으로 롤백되고 에러를 받는다","DB가 재시작된다"], ans: 1, why: "그래서 트랜잭션 코드에는 데드락 에러에 대한 재시도 로직이 흔히 필요합니다." },
      { q: "데드락이 '가능해지는' 조건은?", opts: ["4가지 조건 중 하나라도 성립","4가지 조건이 모두 성립","자원이 2개 이상이면 항상"], ans: 1, why: "필요조건이므로 전부 성립해야 합니다. 역으로 설계자는 하나만 무너뜨리면 됩니다." },
    ],
  },
  8: {
    body: "<h3>무엇이 일어나는가</h3><p>CPU가 실행 대상을 바꿀 때, 현재 작업의 레지스터·PC 등 실행 상태를 저장하고 다음 작업의 것을 복원합니다. 프로세스 간 전환이면 <b>주소 공간(페이지 테이블)까지 교체</b>되므로 스레드 간 전환보다 무겁습니다.</p><h3>진짜 비용은 간접 비용</h3><p>저장/복원 자체(직접 비용)는 ~1µs 수준입니다. 더 큰 것은 <b>간접 비용</b>: 전환 후 캐시와 TLB에 이전 작업의 데이터가 남아 있어, 새 작업이 한동안 캐시 미스 폭탄을 맞습니다(캐시 오염). Day 2에서 본 것처럼 미스 하나가 100배 손해이므로, 잦은 전환은 \"일하는 시간보다 워밍업 시간이 긴\" 상태를 만듭니다.</p><h3>스레드 풀과 이벤트 루프의 존재 이유</h3><p>요청마다 스레드를 만들면(thread-per-request) 수천 스레드가 스위칭을 반복하며 CPU를 낭비합니다. 그래서 <b>스레드 풀</b>은 스레드 수를 코어 수 근처로 고정해 스위칭을 최소화합니다. Node는 더 나아가 <b>스레드 1개로 I/O를 다중화</b>(Day 10)해 스위칭 비용 자체를 회피합니다 — 수만 동시 연결을 감당하는 비결이 \"빨라서\"가 아니라 \"전환하지 않아서\"입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 190\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"26\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">컨텍스트 스위칭의 비용 구조</text><rect x=\"20\" y=\"44\" width=\"120\" height=\"34\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"80\" y=\"66\" text-anchor=\"middle\" font-size=\"11\">작업 A 실행</text><rect x=\"150\" y=\"44\" width=\"90\" height=\"34\" rx=\"6\" fill=\"#F7D9D5\" stroke=\"#B3392E\"/><text x=\"195\" y=\"60\" text-anchor=\"middle\" font-size=\"10\">저장/복원</text><text x=\"195\" y=\"72\" text-anchor=\"middle\" font-size=\"9.5\" fill=\"#B3392E\">직접 ~1µs</text><rect x=\"250\" y=\"44\" width=\"180\" height=\"34\" rx=\"6\" fill=\"#F7D9D5\" stroke=\"#B3392E\" stroke-dasharray=\"4 3\"/><text x=\"340\" y=\"60\" text-anchor=\"middle\" font-size=\"10\">캐시·TLB 미스 구간</text><text x=\"340\" y=\"72\" text-anchor=\"middle\" font-size=\"9.5\" fill=\"#B3392E\">간접 비용 — 보통 이게 더 크다</text><rect x=\"440\" y=\"44\" width=\"180\" height=\"34\" rx=\"6\" fill=\"#DCE3ED\"/><text x=\"530\" y=\"66\" text-anchor=\"middle\" font-size=\"11\">작업 B 제 속도 도달</text><text x=\"20\" y=\"118\" font-size=\"11.5\" fill=\"#5F6B7E\">thread-per-request: 스레드 5,000개 → 전환이 잦아 위 빨간 구간이 CPU 시간을 잠식</text><text x=\"20\" y=\"142\" font-size=\"11.5\" fill=\"#2E6B4F\">스레드 풀: 스레드 ≈ 코어 수 → 전환 최소화</text><text x=\"20\" y=\"166\" font-size=\"11.5\" fill=\"#2E6B4F\">Node 이벤트 루프: 스레드 1개로 I/O 다중화 → 전환 비용 자체를 회피</text></svg>",
    quiz: [
      { q: "프로세스 간 전환이 스레드 간 전환보다 비싼 이유는?", opts: ["프로세스가 더 많은 레지스터를 쓰기 때문","주소 공간(페이지 테이블) 교체가 추가되고 TLB가 무효화되기 때문","OS가 프로세스를 더 좋아하기 때문"], ans: 1, why: "같은 프로세스의 스레드는 주소 공간을 공유하므로(Day 3) 그 부분을 건너뜁니다." },
      { q: "컨텍스트 스위칭의 간접 비용이란?", opts: ["저장해야 할 레지스터 개수","전환 후 캐시·TLB가 식어 새 작업이 미스를 연발하는 것","스케줄러의 계산 시간"], ans: 1, why: "직접 비용(~1µs)보다 이 '워밍업 손실'이 큰 경우가 많습니다." },
      { q: "CPU 4코어 서버에서 CPU 집약 작업용 스레드를 4,000개 만들면?", opts: ["4,000배 빨라진다","처리량은 그대로거나 오히려 감소한다 — 스위칭 오버헤드 때문","메모리만 더 쓰고 속도는 동일하다"], ans: 1, why: "동시에 실행 가능한 건 4개뿐입니다. 나머지는 전환 비용과 (스택) 메모리만 낭비합니다. CPU-bound 작업의 적정 스레드 수 ≈ 코어 수인 이유입니다." },
    ],
  },
  9: {
    body: "<h3>두 개의 세계</h3><p>CPU에는 <b>유저 모드</b>와 <b>커널 모드</b>가 있습니다. 디스크, 네트워크 카드, 다른 프로세스의 메모리 같은 자원은 커널 모드에서만 접근 가능합니다. 아무 프로그램이나 디스크를 직접 긁을 수 있다면 격리도 보안도 없기 때문입니다.</p><h3>시스템 콜 = 커널에 보내는 요청</h3><p>유저 프로그램이 파일을 읽고 싶으면 <b>시스템 콜</b>(<code>read</code>, <code>write</code>, <code>open</code>, <code>fork</code>, <code>mmap</code>…)을 통해 커널에 위탁합니다. trap 명령으로 커널 모드에 진입 → 커널이 검증 후 수행 → 결과와 함께 유저 모드 복귀. 여러분이 쓰는 모든 I/O API의 바닥에는 시스템 콜이 있습니다 — <code>fs.readFile</code>도, <code>fetch</code>도, <code>console.log</code>(stdout에 <code>write</code>)도.</p><h3>비용과 최적화</h3><p>모드 전환은 공짜가 아닙니다(전환 + 캐시 영향). 그래서 고전적 최적화가 <b>시스템 콜 횟수 줄이기</b>입니다: 1바이트씩 1,000번 <code>write</code> 하는 대신 버퍼에 모아 한 번에 쓰기. 스트림과 버퍼링 I/O가 빠른 이유의 절반이 이것입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 200\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><defs><marker id=\"a9\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#5F6B7E\"/></marker></defs><rect x=\"20\" y=\"20\" width=\"600\" height=\"70\" rx=\"10\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"40\" y=\"45\" font-size=\"12\" font-weight=\"700\" fill=\"#D97D00\">유저 모드</text><text x=\"40\" y=\"68\" font-size=\"11\" fill=\"#1B2432\">애플리케이션 코드 · fs.readFile(...) 호출</text><rect x=\"20\" y=\"120\" width=\"600\" height=\"70\" rx=\"10\" fill=\"#DCE3ED\" stroke=\"#5F6B7E\"/><text x=\"40\" y=\"145\" font-size=\"12\" font-weight=\"700\" fill=\"#5F6B7E\">커널 모드</text><text x=\"40\" y=\"168\" font-size=\"11\" fill=\"#1B2432\">권한 검증 → 디스크 드라이버로 읽기 수행 → 결과 복사</text><path d=\"M250,90 L250,118\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a9)\"/><text x=\"258\" y=\"109\" font-size=\"10.5\" fill=\"#B3392E\">trap (read 시스템 콜)</text><path d=\"M480,120 L480,92\" stroke=\"#2E6B4F\" stroke-width=\"1.5\" marker-end=\"url(#a9)\"/><text x=\"488\" y=\"109\" font-size=\"10.5\" fill=\"#2E6B4F\">결과와 함께 복귀</text></svg>",
    quiz: [
      { q: "유저 모드 프로그램이 디스크에 직접 접근할 수 없는 이유는?", opts: ["디스크가 너무 느려서","격리·보안을 위해 — 임의 접근을 허용하면 다른 프로세스/파일 보호가 불가능해서","CPU에 디스크 명령어가 없어서"], ans: 1, why: "모든 자원 접근을 커널이라는 관문으로 통일해야 권한 검증이 가능합니다." },
      { q: "<code>console.log(\"hi\")</code>는 시스템 콜을 유발하는가?", opts: ["아니다 — 순수 JS 함수다","그렇다 — 결국 stdout에 대한 write 시스템 콜로 이어진다","브라우저에서만 유발한다"], ans: 1, why: "그래서 대량 로그가 성능에 실제 영향을 줍니다. 핫 루프 안의 console.log가 벤치마크를 왜곡하는 이유이기도 합니다." },
      { q: "1바이트씩 10,000번 쓰기보다 버퍼에 모아 한 번에 쓰는 게 빠른 주된 이유는?", opts: ["디스크 용량을 아껴서","시스템 콜(모드 전환) 횟수가 10,000회 → 1회로 줄어서","CPU 클럭이 올라가서"], ans: 1, why: "전환 비용 × 횟수가 절감의 본질입니다. 버퍼링 스트림의 존재 이유입니다." },
    ],
  },
  10: {
    body: "<h3>세 가지 I/O 방식</h3><p><b>Blocking</b>: <code>read</code>를 부르면 데이터가 올 때까지 스레드가 잠듭니다. 코드가 단순하지만, 연결 1만 개를 다루려면 스레드 1만 개가 필요합니다(c10k 문제) — Day 8에서 본 스위칭·메모리 비용이 폭발합니다.</p><p><b>Non-blocking</b>: 즉시 반환합니다. 데이터가 없으면 \"없음\"이라고 답하므로, 계속 물어봐야(폴링) 해서 그 자체로는 CPU 낭비입니다.</p><p><b>I/O 멀티플렉싱</b>: 커널에게 \"이 1만 개 소켓 중 <b>준비된 게 생기면 알려줘</b>\"라고 위임합니다. 고전 <code>select</code>는 매 호출마다 전체 목록을 넘기고 커널이 전부 스캔(O(n))하지만, Linux <code>epoll</code>/BSD <code>kqueue</code>는 관심 목록을 커널에 등록해 두고 <b>준비된 것만</b> 돌려받습니다 — 연결 수가 늘어도 비용이 거의 늘지 않습니다.</p><h3>Node의 정체</h3><p>Node의 이벤트 루프(libuv)는 epoll/kqueue 위에 서 있습니다. 스레드 1개가 수만 소켓을 감시하다 준비된 이벤트의 콜백만 실행 — Day 8의 결론(전환하지 않는 것이 비결)이 완성됩니다. 단, 파일 I/O는 OS의 논블로킹 지원이 불완전해 libuv <b>스레드 풀</b>(기본 4개)이 대신 수행합니다. 네트워크는 이벤트 루프, 파일은 스레드 풀 — Node의 이중 구조입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 230\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"26\" font-size=\"12\" font-weight=\"700\" fill=\"#1B2432\">1만 연결을 다루는 두 방법</text><rect x=\"20\" y=\"42\" width=\"290\" height=\"150\" rx=\"10\" fill=\"#fff\" stroke=\"#B3392E\"/><text x=\"165\" y=\"66\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"#B3392E\">Blocking + 스레드 1만 개</text><g font-size=\"10.5\" fill=\"#5F6B7E\" text-anchor=\"middle\"><text x=\"165\" y=\"92\">스레드마다 스택 메모리</text><text x=\"165\" y=\"112\">대부분 잠들어 있음</text><text x=\"165\" y=\"132\">깨어날 때마다 컨텍스트 스위칭</text><text x=\"165\" y=\"162\" fill=\"#B3392E\" font-weight=\"600\">비용이 연결 수에 비례해 폭발</text></g><rect x=\"330\" y=\"42\" width=\"290\" height=\"150\" rx=\"10\" fill=\"#fff\" stroke=\"#2E6B4F\"/><text x=\"475\" y=\"66\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"#2E6B4F\">epoll + 이벤트 루프 (Node)</text><g font-size=\"10.5\" fill=\"#5F6B7E\" text-anchor=\"middle\"><text x=\"475\" y=\"92\">스레드 1개가 전체 감시</text><text x=\"475\" y=\"112\">커널이 \"준비된 것만\" 통보</text><text x=\"475\" y=\"132\">준비된 이벤트의 콜백만 실행</text><text x=\"475\" y=\"162\" fill=\"#2E6B4F\" font-weight=\"600\">연결 수가 늘어도 비용 거의 일정</text></g><text x=\"320\" y=\"218\" text-anchor=\"middle\" font-size=\"11\" fill=\"#5F6B7E\">단, Node의 파일 I/O는 libuv 스레드 풀(기본 4개)이 수행 — 네트워크와 파일의 이중 구조</text></svg>",
    quiz: [
      { q: "blocking I/O가 대규모 동시 연결(c10k)에 부적합한 근본 이유는?", opts: ["read 시스템 콜이 존재하지 않아서","연결 수만큼 스레드가 필요해 메모리·스위칭 비용이 폭발해서","TCP가 1만 연결을 지원하지 않아서"], ans: 1, why: "연결 대부분은 '기다리는 중'인데, 기다림 하나에 스레드 하나를 배정하는 것이 낭비의 원인입니다." },
      { q: "select 대비 epoll의 핵심 개선은?", opts: ["더 많은 파일을 열 수 있다","관심 목록을 커널에 등록해 두고 준비된 fd만 돌려받는다 — 매번 전체 스캔 불필요","유저 모드에서 실행된다"], ans: 1, why: "select는 호출마다 O(n) 스캔, epoll은 준비된 것만 O(1)에 가깝게 통보합니다. 연결 수 확장의 열쇠입니다." },
      { q: "Node에서 <code>fs.readFile</code>이 이벤트 루프가 아닌 스레드 풀에서 처리되는 이유는?", opts: ["파일이 네트워크보다 커서","OS의 파일 논블로킹 I/O 지원이 불완전해서","fs 모듈이 C로 작성돼서"], ans: 1, why: "그래서 파일 I/O를 동시에 5개 이상 걸면(기본 풀 4개) 대기가 생길 수 있습니다 — UV_THREADPOOL_SIZE가 존재하는 이유입니다." },
    ],
  },
};
