import type { Lesson } from "./types";

// Phase II 전반부 (Day 11-15). Day 16-25는 이후 배치에서 추가.
export const PHASE2: Record<number, Lesson> = {
  11: {
    body: "<h3>Big-O는 무엇을 재는 언어인가</h3>\n<p>같은 알고리즘도 내 맥북과 서버에서 걸리는 시간이 다릅니다. 그래서 초 단위 측정 대신 <b>\"입력이 커질 때 연산량이 어떤 비율로 증가하는가\"</b>만 남기고 나머지(기계, 언어, 상수)를 전부 지우는 표기법이 필요합니다. 그 언어가 점근 표기법입니다.</p>\n<h3>정의를 정확히: O, Ω, Θ</h3>\n<p><b>f(n) = O(g(n))</b>의 수학적 정의: <b>어떤 양수 c와 n₀가 존재해서, n ≥ n₀인 모든 n에 대해 f(n) ≤ c·g(n)</b>. 말로 풀면 \"충분히 큰 n부터는, g에 적당한 상수를 곱한 것이 f를 덮는다(상한)\".</p>\n<p>예제로 증명 감각을 잡아봅시다. f(n) = 3n² + 5n + 7은 O(n²)인가? n ≥ 6이면 5n + 7 ≤ n²이므로 3n² + 5n + 7 ≤ 4n². 즉 <b>c = 4, n₀ = 6</b>을 잡으면 정의가 성립합니다. 여기서 두 가지가 보입니다: <b>상수를 버릴 수 있는 근거는 \"c를 내 마음대로 고를 수 있어서\"</b>이고, <b>저차항을 버릴 수 있는 근거는 \"n₀ 이후, 즉 충분히 큰 n만 보면 되어서\"</b>입니다. 외운 규칙이 아니라 정의에서 나오는 자유입니다.</p>\n<p>나머지 둘은 방향만 다릅니다. <b>Ω(오메가)</b>는 하한: f(n) ≥ c·g(n). <b>Θ(세타)</b>는 상한과 하한이 같은 것, 즉 \"딱 그 증가율\". 병합 정렬의 시간은 O(n log n)이면서 Ω(n log n)이므로 Θ(n log n)입니다.</p>\n<h3>가장 흔한 오해 세 가지</h3>\n<p><b>오해 ① \"O = 최악의 경우\"</b>. 아닙니다. 이건 두 개의 독립된 축이 뒤섞인 것입니다. 축 하나: 어떤 <i>케이스</i>를 분석하나(최선/평균/최악). 축 둘: 그 결과를 어떤 <i>표기</i>로 쓰나(O/Ω/Θ). 그래서 \"퀵소트는 <b>최악의 경우</b> Θ(n²)이고 <b>평균</b> Θ(n log n)이다\"처럼 케이스마다 표기가 붙습니다. O가 최악과 자주 엮이는 건 단지 \"최악의 상한\"이 가장 유용한 보장이라 관습적으로 많이 쓰기 때문입니다.</p>\n<p><b>오해 ② \"이진 탐색이 O(n)이라고 하면 틀렸다\"</b>. 정의상으로는 참입니다 — O는 상한이므로 log n ≤ c·n은 당연히 성립하고, 느슨할 뿐 거짓이 아닙니다. 일상 대화에서 \"O(n)이야\"라고 말할 때 우리는 사실 Θ의 의미(딱 맞는 증가율)로 쓰고 있습니다. 정의와 관습을 구분해 두면 면접에서 흔들리지 않습니다.</p>\n<p><b>오해 ③ \"O(1)은 O(n)보다 항상 빠르다\"</b>. 점근 표기는 <b>충분히 큰 n</b>에서의 이야기입니다. 원소 3개짜리 배열에서는 해시 계산(상수가 큰 O(1))보다 그냥 선형 탐색이 빠를 수 있습니다. 상수와 작은 n의 세계는 Day 13에서 본격적으로 다룹니다.</p>\n<h3>증가율의 체급 차이를 몸으로</h3>\n<p>n = 1,000,000일 때 대략의 연산 수: log₂n ≈ <b>20</b>, n = <b>100만</b>, n log n ≈ <b>2,000만</b>, n² = <b>1조</b>, 2ⁿ = 우주의 원자 수보다 큼. n²와 n log n의 간격은 \"조금 느림\"이 아니라 <b>5만 배</b>입니다. 알고리즘 선택이 하드웨어 업그레이드보다 힘이 센 이유가 이 숫자에 있습니다.</p>",
    svg: "<svg viewBox=\"0 0 640 260\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><line x1=\"60\" y1=\"220\" x2=\"600\" y2=\"220\" stroke=\"#5F6B7E\" stroke-width=\"1.5\"/><line x1=\"60\" y1=\"220\" x2=\"60\" y2=\"20\" stroke=\"#5F6B7E\" stroke-width=\"1.5\"/><text x=\"330\" y=\"248\" text-anchor=\"middle\" font-size=\"12\" fill=\"#5F6B7E\">입력 크기 n →</text><text x=\"30\" y=\"120\" font-size=\"12\" fill=\"#5F6B7E\" transform=\"rotate(-90 30 120)\">연산량 →</text><path d=\"M60,220 C200,208 400,200 600,196\" fill=\"none\" stroke=\"#2E6B4F\" stroke-width=\"2\"/><text x=\"604\" y=\"200\" font-size=\"11\" fill=\"#2E6B4F\">log n</text><path d=\"M60,220 L600,150\" fill=\"none\" stroke=\"#5F6B7E\" stroke-width=\"2\"/><text x=\"604\" y=\"152\" font-size=\"11\" fill=\"#5F6B7E\">n</text><path d=\"M60,220 C250,190 450,140 600,95\" fill=\"none\" stroke=\"#D97D00\" stroke-width=\"2\"/><text x=\"604\" y=\"98\" font-size=\"11\" fill=\"#D97D00\">n log n</text><path d=\"M60,220 C250,205 420,120 520,30\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"2\"/><text x=\"524\" y=\"30\" font-size=\"11\" fill=\"#B3392E\">n²</text><path d=\"M60,220 C180,215 260,140 300,25\" fill=\"none\" stroke=\"#7A2E8E\" stroke-width=\"2\"/><text x=\"304\" y=\"28\" font-size=\"11\" fill=\"#7A2E8E\">2ⁿ</text><text x=\"70\" y=\"40\" font-size=\"11.5\" fill=\"#1B2432\" font-weight=\"600\">n=10⁶ 기준: log n≈20 · n log n≈2천만 · n²=1조</text></svg>",
    videos: [{"title":"[자료구조 알고리즘] 빅오표기법 기본설명","channel":"엔지니어대한민국","url":"https://www.youtube.com/watch?v=6Iq5iMCVsXA","note":"한글, Big-O 입문 국내 대표 강의"}],
    quiz: [
      { q: "f(n) = 5n + 20일 때, \"f(n) = O(n²)\"라는 명제는?", opts: ["거짓 — f는 O(n)이지 O(n²)가 아니다","참 — O는 상한이므로 성립한다. 다만 딱 맞는 표기는 Θ(n)","n₀ 값에 따라 참/거짓이 달라진다"], ans: 1, why: "O(n²)는 \"n²에 상수를 곱하면 f를 덮는다\"는 뜻이고 이건 자명하게 참입니다. 느슨한 상한도 상한입니다. 딱 맞는 증가율을 말하고 싶으면 Θ(n)." },
      { q: "\"퀵소트는 최악의 경우 Θ(n²), 평균 Θ(n log n)\" — 이 문장은 모순인가?", opts: ["모순이다. 알고리즘의 복잡도는 하나여야 한다","모순이 아니다. 분석하는 케이스(최악/평균)와 표기법(O/Ω/Θ)은 독립된 축이다","Θ 대신 O를 썼어야만 참이다"], ans: 1, why: "케이스별로 시간 함수 자체가 다르고, 각각을 어떤 표기로 쓰는지는 별개의 문제입니다. \"O = 최악\"이라는 오해를 버리는 것이 오늘의 핵심입니다." },
      { q: "Big-O에서 상수 계수(3n² → n²)를 버려도 되는 정의상의 근거는?", opts: ["컴퓨터가 충분히 빨라서","정의에서 상수 c를 자유롭게 고를 수 있기 때문","상수는 측정이 불가능하기 때문"], ans: 1, why: "f ≤ c·g의 c가 자유이므로 계수는 c에 흡수됩니다. 저차항은 \"n ≥ n₀만 보면 된다\"는 조건이 흡수합니다." },
      { q: "원소가 3개뿐인 배열에서 특정 값 찾기 — O(1) 해시 조회와 O(n) 선형 탐색 중 무엇이 빠른가?", opts: ["항상 해시","항상 선형 탐색","단정할 수 없다 — 점근 표기는 큰 n에서의 이야기이고, 작은 n에서는 상수가 지배한다"], ans: 2, why: "해시 계산 + 버킷 접근의 상수 비용이 세 번의 비교보다 클 수 있습니다. Big-O는 성능의 전부가 아니라 '증가율'만 말해줍니다(Day 13에서 계속)." },
    ],
  },
  12: {
    body: "<h3>원칙: 줄 수가 아니라 \"총 실행 횟수\"</h3>\n<p>복잡도 계산이 헷갈리는 이유의 8할은 코드의 <i>모양</i>(중첩 깊이)을 세기 때문입니다. 세야 하는 건 <b>가장 안쪽 작업이 총 몇 번 실행되는가</b>입니다. 모양은 힌트일 뿐 답이 아닙니다 — 아래 투 포인터가 그 반례입니다.</p>\n<h3>루프 패턴 카탈로그</h3>\n<p><b>① 연속 루프</b>: O(n) 루프 뒤에 O(m) 루프 → O(n + m). 곱이 아니라 합입니다(중첩이 아니니까).</p>\n<p><b>② 종속 중첩</b>: <code>for(i=0..n) for(j=i+1..n)</code> → 내부 실행 횟수는 (n−1) + (n−2) + … + 1 = n(n−1)/2 → <b>O(n²)</b>. \"절반짜리 이중 루프도 n²\"라는 것, 그리고 그 이유(등차수열의 합)를 함께 기억하세요.</p>\n<p><b>③ 절반 감소 / 배증</b>: <code>while(n &gt; 1) n = n/2</code> → n이 1이 되기까지 나누는 횟수 = log₂n → <b>O(log n)</b>. <code>for(i=1; i&lt;n; i*=2)</code>도 동일. <b>\"매 스텝 곱하거나 나누면 log\"</b>가 판별 신호입니다.</p>\n<p><b>④ 투 포인터</b>: <code>while(l &lt; r)</code> 안에서 매번 l++ 또는 r--. 루프가 하나든 둘이든, <b>두 포인터의 총 이동량이 합쳐서 최대 n</b>이므로 O(n)입니다. 슬라이딩 윈도우도 같은 논증: 오른쪽 끝도 왼쪽 끝도 각각 n번 이상 못 움직입니다. 이게 \"모양이 아니라 총 작업량\"의 대표 사례입니다.</p>\n<p><b>⑤ 숨은 비용</b>: 루프 안의 한 줄이 O(1)이 아닐 수 있습니다. JS에서 가장 흔한 함정 둘:</p>\n<pre><code>let s = \"\";\nfor (const x of arr) s += x;        // 문자열은 불변 → 매번 복사 → O(n²)\n                                     // (엔진 최적화로 완화되지만 보장은 아님)\nfor (const x of arr)\n  if (list.includes(x)) ...          // includes가 O(n) → 전체 O(n²)\n                                     // Set으로 바꾸면 O(n)</code></pre>\n<h3>재귀: 점화식을 세우고, 트리로 푼다</h3>\n<p>재귀 함수의 시간은 <b>점화식</b>으로 적습니다. T(n) = (재귀 호출들) + (호출 한 번의 자체 작업). 대표 셋:</p>\n<p>· <b>T(n) = T(n/2) + O(1)</b> → 이진 탐색 → O(log n)<br>· <b>T(n) = 2T(n/2) + O(n)</b> → 병합 정렬 → O(n log n)<br>· <b>T(n) = 2T(n−1) + O(1)</b> → 나이브 피보나치 → O(2ⁿ)</p>\n<p>푸는 직관은 <b>재귀 트리</b>입니다(아래 도식). T(n) = 2T(n/2) + n을 그리면: 루트에서 n의 작업, 다음 레벨은 n/2짜리 둘 = 합 n, 그다음 n/4짜리 넷 = 합 n… <b>레벨마다 합이 n이고 레벨 수가 log n</b> → n log n. 공식 암기가 아니라 이 그림이 본체입니다.</p>\n<h3>마스터 정리는 이 그림의 요약</h3>\n<p>T(n) = aT(n/b) + f(n)에서 잎의 개수는 n^(log_b a)입니다. 이제 질문은 하나: <b>잎에서의 총 작업과 루트의 작업 f(n) 중 누가 큰가?</b> ① 잎이 지배 → T = Θ(n^(log_b a)) ② 균형(레벨마다 비슷) → T = Θ(f(n)·log n) ③ 루트가 지배 → T = Θ(f(n)). 병합 정렬은 a=2, b=2라 n^(log₂2)=n = f(n) — 균형 케이스라 n log n. 케이스 암기가 아니라 \"누가 지배하나\"라는 질문으로 기억하세요.</p>",
    svg: "<svg viewBox=\"0 0 640 250\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"24\" font-size=\"12.5\" font-weight=\"700\" fill=\"#1B2432\">재귀 트리: T(n) = 2T(n/2) + n</text><g text-anchor=\"middle\" font-size=\"11\"><rect x=\"270\" y=\"40\" width=\"100\" height=\"26\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"320\" y=\"57\">n</text><rect x=\"150\" y=\"92\" width=\"80\" height=\"26\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"190\" y=\"109\">n/2</text><rect x=\"410\" y=\"92\" width=\"80\" height=\"26\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"450\" y=\"109\">n/2</text><rect x=\"90\" y=\"144\" width=\"60\" height=\"24\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"120\" y=\"160\">n/4</text><rect x=\"180\" y=\"144\" width=\"60\" height=\"24\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"210\" y=\"160\">n/4</text><rect x=\"380\" y=\"144\" width=\"60\" height=\"24\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"410\" y=\"160\">n/4</text><rect x=\"470\" y=\"144\" width=\"60\" height=\"24\" rx=\"6\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"500\" y=\"160\">n/4</text></g><line x1=\"300\" y1=\"66\" x2=\"200\" y2=\"90\" stroke=\"#5F6B7E\"/><line x1=\"340\" y1=\"66\" x2=\"440\" y2=\"90\" stroke=\"#5F6B7E\"/><line x1=\"180\" y1=\"118\" x2=\"130\" y2=\"142\" stroke=\"#5F6B7E\"/><line x1=\"200\" y1=\"118\" x2=\"205\" y2=\"142\" stroke=\"#5F6B7E\"/><line x1=\"440\" y1=\"118\" x2=\"412\" y2=\"142\" stroke=\"#5F6B7E\"/><line x1=\"460\" y1=\"118\" x2=\"495\" y2=\"142\" stroke=\"#5F6B7E\"/><g font-size=\"11\" fill=\"#2E6B4F\" font-weight=\"600\"><text x=\"575\" y=\"57\">레벨 합 = n</text><text x=\"575\" y=\"109\">레벨 합 = n</text><text x=\"575\" y=\"160\">레벨 합 = n</text></g><text x=\"320\" y=\"200\" text-anchor=\"middle\" font-size=\"12\" fill=\"#1B2432\">레벨 수 = log₂n  →  총합 = <tspan fill=\"#D97D00\" font-weight=\"700\">n log n</tspan></text><text x=\"320\" y=\"228\" text-anchor=\"middle\" font-size=\"11\" fill=\"#5F6B7E\">마스터 정리 = \"레벨별 합이 아래로 갈수록 커지나(잎 지배), 같나(균형), 작아지나(루트 지배)\"의 요약</text></svg>",
    videos: [{"title":"[자료구조 알고리즘] 빅오표기법 문제풀이","channel":"엔지니어대한민국","url":"https://www.youtube.com/watch?v=QBZnX_P_dj4","note":"한글, 코드 보고 복잡도 읽는 연습 — 오늘 주제와 정확히 일치"},{"title":"YouTube에서 'master theorem examples' 검색","channel":"YouTube 검색","url":"https://www.youtube.com/results?search_query=master%20theorem%20examples%20Abdul%20Bari","note":"영어, Abdul Bari의 마스터 정리 강의 추천"}],
    quiz: [
      { q: "<code>for(let i=0;i&lt;n;i++) for(let j=i+1;j&lt;n;j++) work();</code> — work의 총 실행 횟수와 복잡도는?", opts: ["n번 → O(n)","n(n−1)/2번 → O(n²)","n log n번 → O(n log n)"], ans: 1, why: "(n−1)+(n−2)+…+1의 등차수열 합. '절반짜리' 이중 루프도 상수(1/2)만 다를 뿐 O(n²)입니다." },
      { q: "<code>while(n &gt; 1) n = Math.floor(n/2);</code>의 복잡도는?", opts: ["O(n)","O(log n)","O(√n)"], ans: 1, why: "n을 2로 나눠 1이 되기까지 log₂n번. '매 스텝 곱하거나 나누면 log'." },
      { q: "정렬된 배열에서 <code>while(l &lt; r)</code>로 두 포인터를 안쪽으로 좁혀가는 코드(매 반복 l++ 또는 r--)의 복잡도는?", opts: ["O(n²) — 포인터가 2개니까","O(n) — 두 포인터의 총 이동량이 합쳐서 최대 n","O(n log n)"], ans: 1, why: "모양이 아니라 총 작업량을 셉니다. 각 포인터는 평생 n칸 이상 못 움직입니다." },
      { q: "T(n) = 2T(n/2) + O(n)의 해는? (재귀 트리로 생각)", opts: ["O(n)","O(n log n)","O(n²)"], ans: 1, why: "레벨마다 합이 n, 레벨 수가 log n. 병합 정렬의 점화식이며, Day 21에서 실물로 다시 만납니다." },
    ],
  },
  13: {
    body: "<h3>최악 · 평균 · 상환 — 세 단어를 정확히 가르기</h3>\n<p><b>최악(worst)</b>: 가장 불리한 입력에서의 비용. <b>평균(average)</b>: 입력의 확률 분포를 가정한 기댓값 — 분포 가정이 깨지면(예: 해시 충돌 공격) 무너질 수 있는 약속입니다. <b>상환(amortized)</b>: <b>연산을 연속으로 m번 수행한 총비용을 m으로 나눈 값</b>. 분포 가정이 전혀 없는, 시퀀스 전체에 대한 <b>수학적 보장</b>입니다. \"평균\"과 \"상환\"은 일상어로는 비슷해 보여도 보장의 종류가 다릅니다.</p>\n<h3>대표 예제: 동적 배열의 push</h3>\n<p>JS 배열(V8의 동적 배열)은 용량이 차면 <b>더 큰 메모리를 새로 잡고 전체를 복사</b>합니다. 복사하는 push는 O(n)인데, 왜 push를 \"O(1)\"이라고 부를 수 있을까요?</p>\n<p>용량을 2배씩 늘린다고 하고 빈 배열에서 n번 push한 총 복사량을 세봅시다: 1 + 2 + 4 + 8 + … + n/2 + n ≤ <b>2n</b>. 총비용 O(n)을 n번의 push가 나눠 지므로 <b>push 1회당 상환 O(1)</b>입니다(집계 방법, aggregate method). 가끔 오는 비싼 연산의 비용이 그 앞의 싼 연산들이 \"적립\"해 둔 것으로 상쇄된다 — 이것이 상환 분석의 그림 전부입니다.</p>\n<p>왜 하필 <b>배수</b>로 늘릴까요? 반례로 확인하면 선명해집니다. 매번 용량을 +100씩 <b>고정량</b>으로 늘리면, n번 push의 총 복사량은 100 + 200 + 300 + … ≈ n²/200 → <b>상환 O(n)</b>으로 추락합니다. 기하급수(×2, ×1.5)로 늘려야 총합이 등비수열이 되어 O(n)에 갇힙니다. 해시 테이블 리사이징(Day 15), Timsort의 run 병합까지 — \"가끔 O(n) 재구축, 평소 O(1)\"의 패턴은 전부 이 논리 위에 있습니다.</p>\n<h3>공간 복잡도 — 재귀 깊이도 메모리다</h3>\n<p>공간 복잡도는 입력 외에 추가로 쓰는 <b>보조 공간</b>을 셉니다. 자주 잊는 항목이 <b>콜스택</b>입니다: 깊이 n의 재귀는 스택 프레임 n개 = O(n) 공간이고, JS에서 n이 1만쯤 되면 <code>RangeError: Maximum call stack size exceeded</code>가 실물로 증명해 줍니다. 병합 정렬은 병합용 배열 O(n) + 스택 O(log n), 퀵소트는 제자리 파티셔닝이라 보조 공간이 스택 O(log n)뿐(평균) — Day 21에서 이 차이가 두 알고리즘의 성격을 가릅니다.</p>\n<pre><code>// 시간도 공간도 O(n²)인 흔한 JS 코드\nconst out = arr.reduce((acc, x) =&gt; [...acc, f(x)], []);\n// 매 스텝 acc 전체 복사(1+2+…+n). push나 map이면 O(n)</code></pre>\n<h3>작은 n의 세계: 상수가 왕이다</h3>\n<p>n ≤ 32 정도의 작은 구간에서는 O(n²) 삽입 정렬이 O(n log n) 알고리즘들을 <b>실측으로 이깁니다</b> — 비교·이동이 단순하고(상수 작음), 접근이 순차적이라 캐시 친화적(Day 2)이기 때문입니다. 그래서 V8의 sort와 Python의 Timsort는 작은 구간을 삽입 정렬로 처리하는 하이브리드입니다(Day 23). \"점근적으로 나쁜 알고리즘을 일부러 쓰는\" 이 선택이 이상해 보이지 않는다면, 복잡도 3일 치를 제대로 소화한 것입니다.</p>",
    svg: "<svg viewBox=\"0 0 640 240\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"24\" font-size=\"12.5\" font-weight=\"700\" fill=\"#1B2432\">더블링 동적 배열: n번 push의 복사 비용 (용량 1에서 시작)</text><g font-size=\"10\" text-anchor=\"middle\"><rect x=\"40\" y=\"150\" width=\"24\" height=\"12\" fill=\"#D97D00\"/><text x=\"52\" y=\"180\" fill=\"#5F6B7E\">1</text><rect x=\"76\" y=\"138\" width=\"24\" height=\"24\" fill=\"#D97D00\"/><text x=\"88\" y=\"180\" fill=\"#5F6B7E\">2</text><rect x=\"112\" y=\"114\" width=\"24\" height=\"48\" fill=\"#D97D00\"/><text x=\"124\" y=\"180\" fill=\"#5F6B7E\">4</text><rect x=\"148\" y=\"66\" width=\"24\" height=\"96\" fill=\"#D97D00\"/><text x=\"160\" y=\"180\" fill=\"#5F6B7E\">8</text><rect x=\"184\" y=\"150\" width=\"8\" height=\"12\" fill=\"#DCE3ED\"/><rect x=\"196\" y=\"150\" width=\"8\" height=\"12\" fill=\"#DCE3ED\"/><rect x=\"208\" y=\"150\" width=\"8\" height=\"12\" fill=\"#DCE3ED\"/><text x=\"200\" y=\"180\" fill=\"#5F6B7E\">…복사 없는 push들</text></g><text x=\"40\" y=\"205\" font-size=\"11.5\" fill=\"#1B2432\">복사 총량 = 1+2+4+…+n ≤ <tspan font-weight=\"700\" fill=\"#D97D00\">2n</tspan> → push 1회당 <tspan font-weight=\"700\" fill=\"#2E6B4F\">상환 O(1)</tspan></text><text x=\"40\" y=\"228\" font-size=\"11.5\" fill=\"#B3392E\">반례: 매번 +100 고정 증가 → 총량 ≈ n²/200 → 상환 O(n)으로 추락</text><g font-size=\"10.5\" fill=\"#5F6B7E\"><text x=\"360\" y=\"70\">막대 = 그 push에서 발생한 복사량</text><text x=\"360\" y=\"88\">비싼 push는 드물고,</text><text x=\"360\" y=\"104\">그 사이의 싼 push들이 비용을 분담</text></g></svg>",
    videos: [{"title":"YouTube에서 'amortized analysis dynamic array' 검색","channel":"YouTube 검색","url":"https://www.youtube.com/results?search_query=amortized%20analysis%20dynamic%20array","note":"영어 — 이 주제는 한글 단독 강의가 드묾. MIT/Abdul Bari 결과 추천"}],
    quiz: [
      { q: "용량 2배 더블링 동적 배열에 n번 push할 때 복사 연산의 총량은?", opts: ["O(n log n)","O(n) — 1+2+4+…+n ≤ 2n","O(n²)"], ans: 1, why: "등비수열의 합은 마지막 항의 2배 이하. 그래서 push 1회당 상환 O(1)입니다." },
      { q: "용량을 매번 +100씩 고정량으로 늘리면 push의 상환 비용은?", opts: ["여전히 O(1)","O(log n)","O(n) — 총 복사량이 O(n²)이 되므로"], ans: 2, why: "100+200+300+…은 등차수열이라 합이 n²에 비례합니다. '기하급수 증가'가 상환 O(1)의 필수 조건입니다." },
      { q: "깊이가 n인 재귀 함수(각 프레임 O(1))의 공간 복잡도는?", opts: ["O(1) — 변수를 안 만들었으므로","O(n) — 콜스택 프레임이 n개 쌓인다","O(log n)"], ans: 1, why: "콜스택도 메모리입니다. JS에서 스택 오버플로가 그 증거이며, 꼬리 재귀를 루프로 바꾸는 이유이기도 합니다." },
      { q: "\"해시 조회는 평균 O(1)\"과 \"동적 배열 push는 상환 O(1)\" — 두 보장의 차이는?", opts: ["같은 말이다","평균은 입력 분포를 가정한 기댓값, 상환은 분포 가정 없이 연산 시퀀스 총비용에 대한 보장","상환이 평균보다 약한 보장이다"], ans: 1, why: "해시의 평균은 '키가 고르게 퍼진다'는 가정이 깨지면(충돌 공격) 무너지지만, push의 상환 O(1)은 어떤 입력 순서에도 성립하는 수학적 사실입니다." },
    ],
  },
  14: {
    body: "<h3>메모리 배치가 모든 것을 결정한다</h3>\n<p><b>배열</b>은 연속된 메모리입니다. <code>arr[i]</code>의 주소는 <code>base + i × 원소크기</code> — 곱셈 한 번, 덧셈 한 번으로 끝나는 <b>산술</b>이라 인덱스 접근이 O(1)입니다. <b>연결 리스트</b>는 노드들이 힙 여기저기 흩어져 있고 포인터로만 이어집니다. i번째에 가려면 포인터를 i번 따라가야 하므로 접근이 O(n)입니다.</p>\n<table class=\"cmp\"><tr><th>연산</th><th>동적 배열</th><th>연결 리스트</th></tr><tr><td>인덱스 접근</td><td><b>O(1)</b></td><td>O(n)</td></tr><tr><td>탐색(값으로)</td><td>O(n)</td><td>O(n)</td></tr><tr><td>끝에 추가</td><td><b>상환 O(1)</b> (Day 13)</td><td>O(1) (tail 포인터 보유 시)</td></tr><tr><td>앞에 추가</td><td>O(n) — 전체 밀기</td><td><b>O(1)</b></td></tr><tr><td>중간 삽입/삭제</td><td>O(n) — 밀기</td><td>O(1)<b>*</b> — 단, 그 위치까지 가는 게 O(n)</td></tr></table>\n<p>표의 <b>*</b>가 오늘의 급소입니다. \"연결 리스트는 중간 삽입이 O(1)\"이라는 교과서 문장은 <b>삽입 지점의 노드를 이미 손에 쥐고 있을 때</b>만 참입니다. 인덱스나 값으로 위치를 찾아야 한다면 탐색 O(n)이 앞에 붙어, 실전에서는 배열과 다를 게 없어집니다.</p>\n<h3>Big-O가 같아도 실측은 다르다 (Day 2 회수)</h3>\n<p>두 자료구조 모두 전체 순회는 O(n)입니다. 하지만 실측하면 배열이 <b>수 배~수십 배</b> 빠릅니다. 배열 순회는 캐시 라인(64B) 하나로 원소 여러 개를 처리하고 프리페처가 다음 라인을 미리 당겨오지만, 연결 리스트는 노드마다 임의 위치로 점프해 거의 매번 캐시 미스(~100ns)를 냅니다. 여기에 노드마다 포인터 저장 공간(8B+)과 할당 오버헤드도 추가됩니다. <b>현대 하드웨어에서 기본 선택은 압도적으로 동적 배열</b>이고, 이는 취향이 아니라 캐시 구조의 귀결입니다.</p>\n<h3>그럼에도 연결 리스트가 이기는 자리</h3>\n<p>조건은 명확합니다: <b>삽입/삭제 지점의 참조를 항상 쥐고 있고, 그 연산이 지배적일 때</b>. 대표 사례가 <b>LRU 캐시</b>입니다 — 해시맵으로 노드를 O(1)에 찾고, 이중 연결 리스트로 그 노드를 O(1)에 뽑아 맨 앞으로 옮깁니다(두 자료구조의 합체). 그 외에 O(1) splice가 필요한 큐/덱 구현 등. \"언제 쓰나\"의 답이 이렇게 좁다는 것 자체가 오늘의 결론입니다.</p>\n<h3>JS의 배열은 무엇인가</h3>\n<p>JS의 <code>Array</code>는 동적 배열입니다(V8 elements 저장소). 그래서 <code>push</code>는 상환 O(1)(Day 13 그대로), <code>unshift</code>와 중간 <code>splice</code>는 전체 밀기라 O(n)입니다. 큐가 필요할 때 <code>shift()</code>를 루프에서 쓰면 O(n²)가 되는 고전 함정 — 인덱스 포인터를 쓰거나 덱 구현을 쓰세요. 그리고 Day 2에서 본 대로, 객체 배열은 \"포인터의 배열\"이라 순회 시 연결 리스트의 병(캐시 미스)을 일부 공유한다는 것까지 엮으면 오늘 그림이 완성됩니다.</p>",
    svg: "<svg viewBox=\"0 0 640 230\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"24\" font-size=\"12.5\" font-weight=\"700\" fill=\"#1B2432\">배열: 연속 메모리 → 주소 = base + i×size, 캐시 라인에 여러 원소</text><g font-size=\"11\" text-anchor=\"middle\"><rect x=\"40\" y=\"36\" width=\"52\" height=\"30\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"66\" y=\"56\">10</text><rect x=\"92\" y=\"36\" width=\"52\" height=\"30\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"118\" y=\"56\">20</text><rect x=\"144\" y=\"36\" width=\"52\" height=\"30\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"170\" y=\"56\">30</text><rect x=\"196\" y=\"36\" width=\"52\" height=\"30\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"222\" y=\"56\">40</text><rect x=\"248\" y=\"36\" width=\"52\" height=\"30\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"274\" y=\"56\">50</text></g><rect x=\"36\" y=\"32\" width=\"270\" height=\"38\" rx=\"6\" fill=\"none\" stroke=\"#2E6B4F\" stroke-dasharray=\"5 4\" stroke-width=\"1.5\"/><text x=\"320\" y=\"56\" font-size=\"10.5\" fill=\"#2E6B4F\">← 캐시 라인 하나에 함께 로드</text><text x=\"20\" y=\"120\" font-size=\"12.5\" font-weight=\"700\" fill=\"#1B2432\">연결 리스트: 흩어진 노드 → 매 이동이 포인터 점프(캐시 미스 가능)</text><g font-size=\"11\" text-anchor=\"middle\"><rect x=\"40\" y=\"140\" width=\"70\" height=\"30\" rx=\"6\" fill=\"#DCE3ED\" stroke=\"#5F6B7E\"/><text x=\"75\" y=\"160\">10 · ●</text><rect x=\"230\" y=\"180\" width=\"70\" height=\"30\" rx=\"6\" fill=\"#DCE3ED\" stroke=\"#5F6B7E\"/><text x=\"265\" y=\"200\">20 · ●</text><rect x=\"420\" y=\"135\" width=\"70\" height=\"30\" rx=\"6\" fill=\"#DCE3ED\" stroke=\"#5F6B7E\"/><text x=\"455\" y=\"155\">30 · ●</text></g><defs><marker id=\"a14\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#B3392E\"/></marker></defs><path d=\"M110,158 C160,168 190,185 228,193\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a14)\"/><path d=\"M300,192 C350,185 385,165 418,152\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a14)\"/><text x=\"540\" y=\"160\" font-size=\"10.5\" fill=\"#B3392E\">점프마다 ~100ns 위험</text></svg>",
    videos: [{"title":"YouTube에서 '배열 vs 연결리스트' 검색","channel":"YouTube 검색","url":"https://www.youtube.com/results?search_query=%EB%B0%B0%EC%97%B4%20%EC%97%B0%EA%B2%B0%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%B0%A8%EC%9D%B4%20%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%20%EA%B0%95%EC%9D%98","note":"한글 — 상위의 테코톡/쉬운코드 영상 추천"},{"title":"Core Dumped 채널 (배열·리스트 메모리 편)","channel":"Core Dumped","url":"https://www.youtube.com/@CoreDumpped","note":"영어, 메모리 배치 관점의 시각화"}],
    quiz: [
      { q: "<code>arr[i]</code>가 O(1)인 근본 이유는?", opts: ["배열이 캐시에 항상 올라가 있어서","주소를 base + i×size 산술로 즉시 계산할 수 있어서","JS 엔진이 최적화해 주기 때문"], ans: 1, why: "연속 메모리이기에 가능한 주소 산술입니다. 연결 리스트는 이 산술이 불가능해 포인터를 따라가야 합니다." },
      { q: "\"연결 리스트는 중간 삽입이 O(1)\"이 실전에서 성립하는 조건은?", opts: ["리스트가 정렬되어 있을 때","삽입 지점 노드의 참조를 이미 쥐고 있을 때","노드 수가 적을 때"], ans: 1, why: "위치를 찾아야 한다면 탐색 O(n)이 선행됩니다. LRU 캐시가 해시맵을 붙이는 이유가 바로 '참조를 O(1)에 쥐기 위해서'입니다." },
      { q: "배열과 연결 리스트 모두 순회는 O(n)인데 실측에서 배열이 수십 배 빠를 수 있는 이유는?", opts: ["배열의 n이 더 작아서","캐시 라인·프리페처가 순차 접근에 최적화되어 있고, 리스트는 점프마다 캐시 미스를 내기 때문","연결 리스트는 GC가 더 자주 돌아서"], ans: 1, why: "Day 2의 결론이 자료구조 선택으로 이어지는 지점입니다. Big-O는 접근 패턴의 비용을 보지 않습니다." },
    ],
  },
  15: {
    body: "<h3>탐색을 '계산'으로 바꾸는 발상</h3>\n<p>배열에서 값을 찾으려면 비교를 반복해야 합니다(O(n), 정렬돼 있으면 O(log n)). 해시 테이블의 발상은 근본적으로 다릅니다: <b>키를 해시 함수에 넣어 저장 위치를 그 자리에서 계산</b>합니다. <code>index = hash(key) % 버킷수</code> — 비교 대신 산술. 평균 O(1) 탐색/삽입/삭제의 원천입니다.</p>\n<h3>충돌은 버그가 아니라 필연</h3>\n<p>키의 가짓수(모든 문자열)는 버킷 수보다 무한히 많으므로, 서로 다른 키가 같은 인덱스에 떨어지는 <b>충돌은 비둘기집 원리상 불가피</b>합니다. 해시 테이블 설계란 곧 충돌 처리 설계입니다. 두 유파:</p>\n<p><b>① 체이닝</b>: 각 버킷을 리스트로 만들어 충돌 항목을 매답니다. 적재율 α = 항목수/버킷수라 할 때 평균 체인 길이가 α이므로 평균 비용은 O(1+α). 구현이 단순하고 삭제가 쉬워 교과서와 다수 구현의 기본형입니다.</p>\n<p><b>② 오픈 어드레싱</b>: 충돌 시 \"옆 칸\"으로 이동(선형 탐사 등)해 빈 자리를 찾습니다. 포인터가 없어 캐시 친화적(Day 2!)이지만, 항목이 몰리는 클러스터링이 생기고 삭제 시 탐사 사슬이 끊기지 않도록 묘비(tombstone) 처리가 필요합니다. V8의 Map, Python dict 등 고성능 구현이 이쪽 계열입니다.</p>\n<h3>리사이징 — Day 13이 그대로 재등장</h3>\n<p>α가 임계치(예: 0.75)를 넘으면 버킷을 2배로 늘리고 <b>모든 항목을 재해싱</b>합니다(그 한 번은 O(n)). 더블링 + 가끔의 전체 재구축 = 동적 배열 push와 정확히 같은 구조이므로, 삽입은 <b>상환 O(1)</b>입니다. 어제의 분석 도구가 오늘의 자료구조를 설명하는 순간입니다.</p>\n<h3>최악 O(n)은 이론이 아니다: HashDoS</h3>\n<p>\"평균 O(1)\"은 키가 고르게 퍼진다는 가정 위의 약속입니다(Day 13의 평균 vs 상환 구분 그대로). 공격자가 <b>같은 버킷에 떨어지는 키 수만 개</b>를 요청 파라미터로 보내면 서버의 해시 테이블이 사실상 연결 리스트가 되어 O(n²) 처리량으로 주저앉습니다 — 2011년 실제로 주요 웹 플랫폼들을 마비시킨 HashDoS 공격입니다. 그래서 현대 런타임(V8 포함)은 프로세스마다 <b>랜덤 시드가 섞인 해시 함수</b>를 써서 충돌 키를 미리 계산할 수 없게 만듭니다.</p>\n<h3>V8에서 이 지식이 닿는 곳</h3>\n<p>반전 하나: V8에서 일반 객체의 프로퍼티 접근은 기본적으로 해시 조회가 <b>아닙니다</b>. 고정된 모양(히든 클래스)의 오프셋 접근이라 더 빠릅니다. 하지만 <code>delete</code>를 남발하거나 키를 동적으로 대량 추가하면 객체가 <b>dictionary mode</b>(진짜 해시 테이블)로 강등되어 느려집니다. 그래서 실무 지침이 나옵니다: <b>동적 키의 대량 추가/삭제/순회가 필요하면 처음부터 <code>Map</code></b>(설계상 해시 테이블, 임의 타입 키, 크기 O(1), 삽입 순 순회)을 쓰고, 모양이 고정된 레코드는 객체를 쓰는 것. 히든 클래스의 전모는 Day 58에서 다룹니다.</p>",
    svg: "<svg viewBox=\"0 0 640 240\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\"><text x=\"20\" y=\"24\" font-size=\"12.5\" font-weight=\"700\" fill=\"#1B2432\">체이닝 해시 테이블: hash(key) % 8</text><g font-size=\"11\"><rect x=\"40\" y=\"44\" width=\"90\" height=\"26\" rx=\"5\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"85\" y=\"61\" text-anchor=\"middle\">\"userId\"</text><rect x=\"40\" y=\"84\" width=\"90\" height=\"26\" rx=\"5\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"85\" y=\"101\" text-anchor=\"middle\">\"email\"</text><rect x=\"40\" y=\"124\" width=\"90\" height=\"26\" rx=\"5\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"85\" y=\"141\" text-anchor=\"middle\">\"phone\"</text></g><defs><marker id=\"a15\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"3\" orient=\"auto\"><path d=\"M0,0L7,3L0,6z\" fill=\"#5F6B7E\"/></marker></defs><path d=\"M130,57 L228,73\" fill=\"none\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a15)\"/><path d=\"M130,97 L228,73\" fill=\"none\" stroke=\"#B3392E\" stroke-width=\"1.5\" marker-end=\"url(#a15)\"/><path d=\"M130,137 L228,168\" fill=\"none\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a15)\"/><text x=\"150\" y=\"48\" font-size=\"10\" fill=\"#B3392E\">충돌!</text><g font-size=\"10.5\" text-anchor=\"middle\"><rect x=\"232\" y=\"40\" width=\"44\" height=\"26\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"254\" y=\"57\" fill=\"#5F6B7E\">[0]</text><rect x=\"232\" y=\"66\" width=\"44\" height=\"26\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"254\" y=\"83\" fill=\"#1B2432\">[1]</text><rect x=\"232\" y=\"92\" width=\"44\" height=\"26\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"254\" y=\"109\" fill=\"#5F6B7E\">[2]</text><rect x=\"232\" y=\"118\" width=\"44\" height=\"26\" fill=\"#EDF1F7\" stroke=\"#D8DFE9\"/><text x=\"254\" y=\"135\" fill=\"#5F6B7E\">…</text><rect x=\"232\" y=\"144\" width=\"44\" height=\"26\" fill=\"#FBEEDC\" stroke=\"#D97D00\"/><text x=\"254\" y=\"161\" fill=\"#1B2432\">[6]</text></g><g font-size=\"10.5\" text-anchor=\"middle\"><rect x=\"300\" y=\"66\" width=\"100\" height=\"26\" rx=\"5\" fill=\"#fff\" stroke=\"#5F6B7E\"/><text x=\"350\" y=\"83\">userId → ●</text><rect x=\"420\" y=\"66\" width=\"100\" height=\"26\" rx=\"5\" fill=\"#fff\" stroke=\"#5F6B7E\"/><text x=\"470\" y=\"83\">email → ∅</text><rect x=\"300\" y=\"144\" width=\"100\" height=\"26\" rx=\"5\" fill=\"#fff\" stroke=\"#5F6B7E\"/><text x=\"350\" y=\"161\">phone → ∅</text></g><line x1=\"400\" y1=\"79\" x2=\"418\" y2=\"79\" stroke=\"#5F6B7E\" stroke-width=\"1.5\" marker-end=\"url(#a15)\"/><text x=\"320\" y=\"215\" text-anchor=\"middle\" font-size=\"11\" fill=\"#5F6B7E\">적재율 α = 항목수/버킷수 · 평균 비용 O(1+α) · α 초과 시 2배 리사이징(상환 O(1), Day 13)</text></svg>",
    videos: [{"title":"[10분 테코톡] 랜디의 해시 테이블","channel":"우아한테크","url":"https://www.youtube.com/watch?v=P3vFRUmfLME","note":"한글, 10분 압축 정리"},{"title":"Hash Table은 프로그래머의 기본기","channel":"포프TV","url":"https://www.youtube.com/watch?v=S7vni1hdsZE","note":"한글, 왜 면접마다 나오는지에 대한 현업 관점"}],
    quiz: [
      { q: "해시 충돌이 '버그'가 아니라 '필연'인 이유는?", opts: ["해시 함수가 아직 불완전해서","가능한 키의 가짓수가 버킷 수보다 많으므로(비둘기집 원리) 어떤 해시 함수라도 충돌을 피할 수 없어서","메모리가 부족해서"], ans: 1, why: "완벽한 해시 함수로 충돌을 없애는 게 아니라, 충돌을 어떻게 처리하느냐(체이닝/오픈 어드레싱)가 설계의 본체입니다." },
      { q: "적재율(load factor)이 임계치를 넘으면 하는 일과 그 비용은?", opts: ["버킷을 2배로 늘리고 전체 재해싱 — 그 1회는 O(n)이지만 삽입은 상환 O(1)","테이블을 잠그고 쓰기를 거부한다","체인을 정렬한다"], ans: 0, why: "동적 배열 더블링(Day 13)과 동일한 구조입니다. '가끔 O(n) 재구축'이 상환 분석으로 정당화됩니다." },
      { q: "V8 기준, 키를 동적으로 대량 추가/삭제하며 크기도 자주 확인하는 컬렉션에 적합한 것은?", opts: ["일반 객체 {} — 가장 가볍다","Map — 설계상 해시 테이블이며, 객체는 delete 남발 시 dictionary mode로 강등된다","배열에 [key, value]를 push"], ans: 1, why: "객체는 '모양이 고정된 레코드'에 최적화되어 있습니다(히든 클래스). 동적 키 워크로드는 Map의 홈그라운드입니다." },
    ],
  },
};
